#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

APP_PATH=/opt/headphones
RUN_AS=headphones
DATA_DIR=/home/headphones/.headphones

switch_repo() {
    if [ -d $APP_PATH ]; then
        rm -Rf $APP_PATH
    fi

    if [ -d $DATA_DIR ]; then
        rm -Rf $DATA_DIR
    fi

    sudo -u $RUN_AS git clone "${1}" -b "${2}" "${APP_PATH}"
}

switch_branch() {
    cd $APP_PATH
    sudo -u $RUN_AS git reset --hard
    sudo -u $RUN_AS git checkout "${1}"
}

repo="$(omv_config_get "//services/headphones/repo")"
branch="$(omv_config_get "//services/headphones/branch")"

# If /opt/headphones does not exists
# must be first clone
if [ ! -d $APP_PATH ]; then
    switch_repo "$repo" "$branch"
    exit 0
fi

# If /opt/headphones exists and is not empty
# fetch current repo and branch
if [ -n "$(ls -A $APP_PATH)" ]; then
    cd $APP_PATH
    current_repo="$(git config --get remote.origin.url)"
    current_branch="$(git rev-parse --abbrev-ref HEAD)"
fi

if [ $repo != $current_repo ]; then
    switch_repo "${repo}" "${branch}"
    exit 0
fi

if [ $branch != $current_branch ]; then
    switch_branch "${branch}"
    exit 0
fi
