#! /bin/sh

### BEGIN INIT INFO
# Provides:          Headphones
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of Headphones
# Description:       starts instance of Headphones using start-stop-daemon
### END INIT INFO

############### EDIT ME ##################
# startup args
DAEMON_OPTS=" Headphones.py -q"

# script name
NAME=headphones

# app name
DESC=headphones

# user
RUN_AS=headphones

# path to app
APP_PATH=/opt/headphones

# path to python bin
DAEMON=/usr/bin/python
PID_FILE=/var/run/headphones/headphones.pid
PID_PATH=/var/run/headphones
############### END EDIT ME ##################

test -x $DAEMON || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

set -e

if [ ! -d $PID_PATH ]; then
    mkdir -p $PID_PATH
fi

chown -R $RUN_AS:users $PID_PATH

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        rm $PID_FILE
    fi
fi

is_running()
{
    if [ ! -e $PID_FILE ]; then
        return 1
    fi
    return 0
}


case "$1" in

    start)
        echo "Starting $DESC"
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        ;;

    stop)
        if is_running; then
            echo "Stopping $DESC"
            start-stop-daemon --stop --pidfile $PID_FILE
        fi
        ;;

    restart|force-reload)
        if is_running; then
            start-stop-daemon --stop --pidfile $PID_FILE
        fi
        echo "Restarting $DESC"
        sleep 15
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        ;;

    status)
        status_of_proc -p $PID_FILE "$DAEMON" "$NAME"
        ;;

    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
