#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
configure)
    if ! omv_config_exists "/config/services/headphones"; then
        echo "Initial configuration."
        object="<enable>0</enable>"
        object="${object}<showtab>0</showtab>"
        omv_config_add_element "/config/services" "headphones" "${object}" true
    fi

    if ! grep -q "^headphones:" /etc/passwd; then
        echo "Adding headphones user..."
        useradd --no-create-home --groups users --no-user-group --shell /usr/sbin/nologin headphones
    else
        echo "headphones user already exists."
    fi

    chown -R headphones:users /opt/headphones
    chown -R headphones:users /etc/init.d/headphones

    ;;
abort-upgrade|abort-remove|abort-deconfigure)
    ;;
*)
    echo "postinst called with unknown argument" >&2
    exit 1
    ;;
esac

exit 0
